insert into roles (role_id, role_number) values (1, 1);
insert into roles (role_id, role_number) values (2, 2);
insert into roles (role_id, role_number) values (3, 3);
-- --------------------------------------------------------
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (1, 'cvanlint0@yale.edu', 'YyOK6KNog9Nu', 'Christalle', 'cbirtwhistle0', '8785492590', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (2, 'fsmitheman1@foxnews.com', 'EwHs2L', 'Flint', 'fducarne1', '2643193601', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (3, 'chackett2@shop-pro.jp', '77sDIA4', 'Colline', 'cdaugherty2', '6435759447', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (4, 'tebbett3@webnode.com', 'vChhAZf', 'Tierney', 'tmerrison3', '1136551706', 'Genderfluid', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (5, 'wrosenzwig4@gmpg.org', '9W391FGWLenr', 'Wyndham', 'wmathias4', '6202075220', 'Bigender', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (6, 'betock5@baidu.com', 'ud5Kd6F', 'Brit', 'btoth5', '3301310329', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (7, 'sbaff6@bizjournals.com', 'p430tOHnoock', 'Siobhan', 'smcconachie6', '3535236048', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (8, 'mpomphrey7@vimeo.com', 'e2tneOuAw7', 'Meridel', 'msnasel7', '1964724987', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (9, 'mskellion8@ed.gov', '1KiOVCU', 'Mil', 'mrosbottom8', '6546296352', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (10, 'ggaley9@g.co', 'jz34OOi', 'Giralda', 'gbradlaugh9', '4977828732', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (11, 'lhinera@sitemeter.com', 'DtOShbVQULUO', 'Lemuel', 'lfollinga', '9124407262', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (12, 'mparagreenb@mayoclinic.com', 'pZWweTlzT7wB', 'Moises', 'mmuirheadb', '1343319485', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (13, 'ocraigheidc@skyrock.com', 'fY43qcZWBmZF', 'Orsa', 'osahnowc', '2981579228', 'Genderfluid', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (14, 'acolkettd@taobao.com', 'qVQcgpRPLZxa', 'Alexia', 'avoiseyd', '8774490010', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (15, 'aweiche@dell.com', 'UwiqEnr0D6', 'Artus', 'aroulliere', '2671883941', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (16, 'tspaltonf@cargocollective.com', '62muntXnOy3', 'Trixi', 'ttuerenaf', '4949086729', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (17, 'tlibrerosg@bloglovin.com', 'dLcD0g5', 'Tabbie', 'tdavidowg', '7728386722', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (18, 'mrendbaekh@sciencedaily.com', 'bsz29qed', 'Mathilde', 'myakunchikovh', '9851170331', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (19, 'hscrauniagei@hugedomains.com', 'tkODcZbs', 'Hilton', 'handresi', '8831982645', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (20, 'awatkinj@answers.com', 'bZnG2H7f', 'Abrahan', 'atrenchj', '6018255779', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (21, 'aborrottk@marketwatch.com', 'GbZuOKhFq', 'Aubine', 'ashellcrossk', '9914555002', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (22, 'cleybanl@wired.com', '0hHaBm', 'Chane', 'csneezeml', '1272692650', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (23, 'bjoderlim@nifty.com', 'AbH301md', 'Billy', 'bkinastanm', '8022860799', 'Genderfluid', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (24, 'icraigien@indiatimes.com', '9jognb', 'Ikey', 'iperduen', '9906856415', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (25, 'ngosneyeo@imdb.com', 'WZFXMsetATG', 'Nathanil', 'ngrenkovo', '5427519622', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (26, 'fpratleyp@theguardian.com', '6LlP6x', 'Ferdy', 'fhurdp', '3076117297', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (27, 'gnilgesq@yahoo.com', '8S7qtocr4syU', 'Glynn', 'gbaccasq', '1038150802', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (28, 'wlambler@biblegateway.com', 'XLW8kBN0Z', 'Wood', 'wbritneyr', '5644513620', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (29, 'cgirodins@networkadvertising.org', 'sKZDakspQt', 'Carson', 'cllorentes', '4824907240', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (30, 'lhoodlasst@latimes.com', 'TaFEoe61w9s', 'Lonnie', 'lcamillot', '1653578239', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (31, 'rmacfadyenu@amazon.co.uk', '01bh4DAIoD', 'Romola', 'rgobbettu', '9847655507', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (32, 'aiowarchv@blogtalkradio.com', 'FDNuZK', 'Alistair', 'ayaninv', '6087631182', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (33, 'lliliew@paginegialle.it', '5saAUTBN', 'Lief', 'lcubbinow', '7673183573', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (34, 'jmulhallx@histats.com', 'WnItEn7IoLlK', 'Jillene', 'jcammidgex', '2387447780', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (35, 'rcharloty@e-recht24.de', 'q6ZOMTME', 'Roxine', 'rsawoody', '9247488181', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (36, 'aperratz@nasa.gov', 'K0VldSAXL76', 'Aubrie', 'apaolucciz', '1067599361', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (37, 'nriditch10@infoseek.co.jp', 'WNzRP7RCPK87', 'Norean', 'nschultz10', '7235709663', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (38, 'egarley11@chronoengine.com', 'yL2q1QSfcC8', 'Eadmund', 'eburgum11', '6895003974', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (39, 'lthebes12@marketwatch.com', 'lVoThC9tVf8y', 'Laurella', 'lruprich12', '4451389499', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (40, 'tyeude13@answers.com', 'ipNOmbgBR', 'Teressa', 'tiacovucci13', '2981963198', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (41, 'mtoland14@shinystat.com', 'Yp4afpHJ', 'Marmaduke', 'mrycroft14', '5062427669', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (42, 'bswales15@microsoft.com', 'fMTUgP', 'Bronny', 'bcowgill15', '2105870038', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (43, 'frowlin16@cdc.gov', 'w1IKSIRlc8', 'Florencia', 'froseveare16', '1473783104', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (44, 'jcard17@theglobeandmail.com', 'YRInInu2', 'Jervis', 'jcodrington17', '2074023518', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (45, 'swhitter18@cbslocal.com', 'ayKh7U', 'Stormi', 'sstothart18', '4261584358', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (46, 'vsapp19@thetimes.co.uk', '00EA2Em', 'Vasili', 'vwearing19', '4963924685', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (47, 'bmilthorpe1a@amazon.de', 'zBMJ7uspCZEK', 'Bev', 'bmeron1a', '7924537727', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (48, 'mpaolino1b@uol.com.br', '2ou1oQcE0z', 'Marga', 'mben1b', '5086120535', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (49, 'acornbill1c@umich.edu', 'zqC0HyPq', 'Alexandrina', 'awarmington1c', '1178129706', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (50, 'agifford1d@who.int', 'Bff4Jw', 'Angel', 'adoust1d', '3607394146', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (51, 'cjones1e@mapquest.com', 'j5wFqaEs4dM', 'Cassius', 'cmanklow1e', '8454775395', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (52, 'cgossipin1f@macromedia.com', 'jnXEE2sUoXE', 'Chris', 'ccockerill1f', '9033205968', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (53, 'fmackeague1g@ocn.ne.jp', 'QbZJPRdNwi5', 'Franzen', 'fpesticcio1g', '3278545708', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (54, 'tscamel1h@google.com', '2khpDwS', 'Tristam', 'tforbear1h', '6848485723', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (55, 'risaac1i@imgur.com', '2GC4wZ', 'Royall', 'rblissett1i', '4941075137', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (56, 'bbletso1j@blinklist.com', 'UkWlbNy0', 'Brody', 'bdunwoody1j', '1459662124', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (57, 'sstebles1k@nba.com', 'NAx5bJPUg', 'Suzi', 'schanner1k', '7134864900', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (58, 'jveld1l@netvibes.com', 'sSVj67vP', 'Johnathon', 'jside1l', '5425094808', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (59, 'kwarters1m@sohu.com', 'YkbA9jzqi', 'Karrie', 'kisselee1m', '2916955223', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (60, 'sgamwell1n@godaddy.com', 'KLXiPfHK2', 'Shanie', 'shalsworth1n', '4614929556', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (61, 'raspel1o@list-manage.com', 'UasbIftRx', 'Romona', 'rtutchell1o', '4357826882', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (62, 'geborn1p@bizjournals.com', 'i0smuoAI02hn', 'Gloria', 'gledbetter1p', '2253618857', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (63, 'aximenez1q@washington.edu', 'zU8zic', 'Antin', 'ajirka1q', '8135226956', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (64, 'dmenhci1r@devhub.com', 'cHs5b1', 'Dominik', 'dbrik1r', '1363672019', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (65, 'rkoppeck1s@sbwire.com', 'eRHmiUyzBr', 'Rey', 'rosharkey1s', '4844633197', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (66, 'kgermaine1t@irs.gov', 'HfvRuz4sDb', 'Kora', 'kaiston1t', '4042473486', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (67, 'lshakespear1u@jugem.jp', '3J3h92Lb2', 'Lammond', 'ltreat1u', '7835185211', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (68, 'slalevee1v@pinterest.com', 'gQ1wBZZq', 'Sherlock', 'shoodless1v', '7997634045', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (69, 'inewnham1w@columbia.edu', 'QyeIsvq8nr', 'Imojean', 'ilacy1w', '6936201204', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (70, 'sscholard1x@ifeng.com', 'mH2dpQ6iAlDH', 'Saunderson', 'smcane1x', '4091586012', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (71, 'bmacquarrie1y@google.com.br', 'SzvJ05rqmSCj', 'Bernetta', 'bmarginson1y', '5262706447', 'Genderqueer', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (72, 'lskilling1z@ibm.com', 'HVsFnDoQ', 'Lyndsey', 'ldaintree1z', '2182987237', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (73, 'rilive20@imdb.com', 'TrOa8iMYS', 'Randie', 'rleheude20', '3517125508', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (74, 'dcofax21@privacy.gov.au', 'fpApUX83', 'Dahlia', 'dattwool21', '9269096863', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (75, 'fcrimes22@wufoo.com', 'ik5QIwz', 'Frasquito', 'fducker22', '8162574464', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (76, 'jgavozzi23@naver.com', 'dHvfvAn9ZLXo', 'Jacinda', 'jtows23', '1831719161', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (77, 'mmacura24@disqus.com', 'dZfvjlKzb4', 'Malvin', 'mdykes24', '4889997797', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (78, 'boade25@washingtonpost.com', 'nbc2mgxLqCbt', 'Bobby', 'bskehan25', '4321527204', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (79, 'gcathery26@house.gov', 'rrUOsOO', 'Glory', 'gkitcat26', '5945937450', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (80, 'dbensley27@google.nl', 'XFsR5io', 'Dody', 'dtrice27', '7185809629', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (81, 'cmichie28@reference.com', 'ViPoZLvc', 'Chery', 'cvedyashkin28', '9384966272', 'Non-binary', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (82, 'gkayes29@harvard.edu', 'veOYkkGI5yY', 'Gray', 'gilson29', '3121749632', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (83, 'ayardley2a@tinypic.com', 'aFx03j9', 'Alfie', 'aharbisher2a', '6225220751', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (84, 'acarryer2b@gnu.org', 'DTTY4Y', 'Aylmer', 'aheale2b', '9381672590', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (85, 'cmarjanovic2c@hp.com', 'chGVKCVd7', 'Cymbre', 'ccovino2c', '3356447390', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (86, 'dniessen2d@quantcast.com', 'rVU7QpAfdv', 'Dyann', 'dmatches2d', '5052788880', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (87, 'rcarlyon2e@who.int', 'V35XDiA', 'Rufe', 'risles2e', '9314629680', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (88, 'mmardling2f@tmall.com', '5mkK4A3A', 'Maribelle', 'mimloch2f', '7491358374', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (89, 'kluckcock2g@mtv.com', 'KOZO4Q', 'Kimberley', 'kmacphaden2g', '3172437456', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (90, 'frattrie2h@biglobe.ne.jp', 'G30SVvYmFDB', 'Felicia', 'fcadalleder2h', '1574775328', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (91, 'mtumielli2i@tinyurl.com', 'seAiSNX0Vasq', 'Maxie', 'msamwyse2i', '4542512312', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (92, 'bzouch2j@addtoany.com', 'eoeivLaJqOn', 'Baron', 'badnam2j', '2757548535', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (93, 'gschurig2k@upenn.edu', '72PTwuvaxv', 'Gonzales', 'gdewicke2k', '6245118264', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (94, 'cbytheway2l@usatoday.com', 'CjlO4NVz7', 'Cletis', 'cmarsy2l', '2422360285', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (95, 'bdeathe2m@fema.gov', 'yKcnwJPcKuy9', 'Brien', 'bjouannisson2m', '4904533778', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (96, 'klebarr2n@sourceforge.net', 'HPEMSGpK', 'Kellen', 'kmartinho2n', '3476367444', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (97, 'kticksall2o@about.me', 'QujgDqh0', 'Kriste', 'kgoodchild2o', '6916620713', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (98, 'dfripp2p@umn.edu', '2YaetdpiJLC', 'Darci', 'dallebone2p', '5147147102', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (99, 'gthraves2q@jimdo.com', 'ztwrevasAc', 'Griswold', 'gtwort2q', '6505064927', 'Male', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (100, 'khospital2r@narod.ru', 'nMP034xfaWAM', 'Kata', 'kjeandet2r', '5247037558', 'Female', 2);
insert into users (user_id, email, password, user_name, nick_name, phone_no, gender, role_id) values (101, 'test1@gmail.com', '123', '이수만', '나많이보고싶었어요?','010-1234-2333','NONE',2);
-- --------------------------------------------------------

insert into topic_tags (topic_id, topic_body) values (1, 'Sundome');
insert into topic_tags (topic_id, topic_body) values (2, 'Film Unfinished, A (Shtikat Haarchion)');
insert into topic_tags (topic_id, topic_body) values (3, 'Illusion Travels by Streetcar (Ilusión viaja en tranvía, La)');
insert into topic_tags (topic_id, topic_body) values (4, 'Kai Po Che!');
insert into topic_tags (topic_id, topic_body) values (5, 'Three Kings');
insert into topic_tags (topic_id, topic_body) values (6, 'Cuban Fury');
insert into topic_tags (topic_id, topic_body) values (7, 'Man Who Left His Will on Film, The (Tôkyô sensô sengo hiwa)');
insert into topic_tags (topic_id, topic_body) values (8, 'Vivien Leigh: Scarlett and Beyond');
insert into topic_tags (topic_id, topic_body) values (9, 'Kaksi kotia (Dagmamman)');
insert into topic_tags (topic_id, topic_body) values (10, 'Chorus Line, A');
insert into topic_tags (topic_id, topic_body) values (11, 'Winnie the Pooh');
insert into topic_tags (topic_id, topic_body) values (12, 'Babes in Arms');
insert into topic_tags (topic_id, topic_body) values (13, 'Battlestar Galactica: The Plan');
insert into topic_tags (topic_id, topic_body) values (14, 'Magic Trip');
insert into topic_tags (topic_id, topic_body) values (15, 'Last Broadcast, The');
insert into topic_tags (topic_id, topic_body) values (16, 'Sada');
insert into topic_tags (topic_id, topic_body) values (17, 'Moment to Remember, A (Nae meorisokui jiwoogae)');
insert into topic_tags (topic_id, topic_body) values (18, 'Libre échange');
insert into topic_tags (topic_id, topic_body) values (19, 'Homecoming');
insert into topic_tags (topic_id, topic_body) values (20, 'Princess Ka''iulani');
insert into topic_tags (topic_id, topic_body) values (21, 'Ruins');
insert into topic_tags (topic_id, topic_body) values (22, 'Confessions of a Window Cleaner');
insert into topic_tags (topic_id, topic_body) values (23, 'Red');
insert into topic_tags (topic_id, topic_body) values (24, 'Private Lives of Elizabeth and Essex, The');
insert into topic_tags (topic_id, topic_body) values (25, 'Conrack');
insert into topic_tags (topic_id, topic_body) values (26, 'Study in Terror, A');
insert into topic_tags (topic_id, topic_body) values (27, 'Prince of Egypt, The');
insert into topic_tags (topic_id, topic_body) values (28, 'Skin, Skin (Käpy selän alla)');
insert into topic_tags (topic_id, topic_body) values (29, 'The Prince');
insert into topic_tags (topic_id, topic_body) values (30, 'Innocent Sleep, The');
insert into topic_tags (topic_id, topic_body) values (31, 'Classmates');
insert into topic_tags (topic_id, topic_body) values (32, 'Sherlock Holmes and the Secret Weapon');
insert into topic_tags (topic_id, topic_body) values (33, 'Kummeli Stories');
insert into topic_tags (topic_id, topic_body) values (34, 'Major League: Back to the Minors');
insert into topic_tags (topic_id, topic_body) values (35, 'Hitch');
insert into topic_tags (topic_id, topic_body) values (36, 'Alive Inside');
insert into topic_tags (topic_id, topic_body) values (37, 'State Fair');
insert into topic_tags (topic_id, topic_body) values (38, 'Last Blitzkrieg, The');
insert into topic_tags (topic_id, topic_body) values (39, 'Chasing Christmas');
insert into topic_tags (topic_id, topic_body) values (40, 'Premature Burial, The');
insert into topic_tags (topic_id, topic_body) values (41, 'Kings of the Sun');
insert into topic_tags (topic_id, topic_body) values (42, 'Heartbreak Hospital');
insert into topic_tags (topic_id, topic_body) values (43, 'Sea Is Watching, The (Umi wa miteita)');
insert into topic_tags (topic_id, topic_body) values (44, 'Night in the Life of Jimmy Reardon, A');
insert into topic_tags (topic_id, topic_body) values (45, 'Mammoth (Mammut)');
insert into topic_tags (topic_id, topic_body) values (46, 'Pharaoh''s Army');
insert into topic_tags (topic_id, topic_body) values (47, 'Prisoner of Paradise');
insert into topic_tags (topic_id, topic_body) values (48, 'Cry Baby Lane');
insert into topic_tags (topic_id, topic_body) values (49, 'Orders to Kill');
insert into topic_tags (topic_id, topic_body) values (50, 'Pie in the Sky');
insert into topic_tags (topic_id, topic_body) values (51, 'Deceived');
insert into topic_tags (topic_id, topic_body) values (52, 'Chelsea on the Rocks');
insert into topic_tags (topic_id, topic_body) values (53, 'Full Moon in Blue Water');
insert into topic_tags (topic_id, topic_body) values (54, 'Dementia 13');
insert into topic_tags (topic_id, topic_body) values (55, 'Ruinss');
insert into topic_tags (topic_id, topic_body) values (56, 'Obsessed');
insert into topic_tags (topic_id, topic_body) values (57, 'If These Walls Could Talk 2');
insert into topic_tags (topic_id, topic_body) values (58, 'London Boulevard');
insert into topic_tags (topic_id, topic_body) values (59, 'Blue Collar');
insert into topic_tags (topic_id, topic_body) values (60, 'Assassination on the Tiber');
insert into topic_tags (topic_id, topic_body) values (61, 'Exodus (Cheut ai kup gei)');
insert into topic_tags (topic_id, topic_body) values (62, 'Night We Never Met, The');
insert into topic_tags (topic_id, topic_body) values (63, 'Mr. Popper''s Penguins');
insert into topic_tags (topic_id, topic_body) values (64, 'Go Go Tales');
insert into topic_tags (topic_id, topic_body) values (65, 'Lucie Aubrac');
insert into topic_tags (topic_id, topic_body) values (66, 'White Palms (Fehér tenyér)');
insert into topic_tags (topic_id, topic_body) values (67, 'Miss Météo');
insert into topic_tags (topic_id, topic_body) values (68, 'When Worlds Collide');
insert into topic_tags (topic_id, topic_body) values (69, 'James and the Giant Peach');
insert into topic_tags (topic_id, topic_body) values (70, 'Taking Chance');
insert into topic_tags (topic_id, topic_body) values (71, 'Pope''s Toilet, The (El bano del Papa)');
insert into topic_tags (topic_id, topic_body) values (72, 'Slave of Love, A (Raba lyubvi)');
insert into topic_tags (topic_id, topic_body) values (73, 'King Arthur');
insert into topic_tags (topic_id, topic_body) values (74, 'About Adam');
insert into topic_tags (topic_id, topic_body) values (75, 'Birdcage Inn (Paran daemun)');
insert into topic_tags (topic_id, topic_body) values (76, 'Lady Dragon');
insert into topic_tags (topic_id, topic_body) values (77, 'Big Buck Bunny');
insert into topic_tags (topic_id, topic_body) values (78, 'My Sassy Girl');
insert into topic_tags (topic_id, topic_body) values (79, 'They Drive by Night');
insert into topic_tags (topic_id, topic_body) values (80, 'Crowd Roars, The');
insert into topic_tags (topic_id, topic_body) values (81, 'I Wake Up Screaming');
insert into topic_tags (topic_id, topic_body) values (82, 'Novena, The (La neuvaine)');
insert into topic_tags (topic_id, topic_body) values (83, 'My Last Five Girlfriends');
insert into topic_tags (topic_id, topic_body) values (84, 'Giliap');
insert into topic_tags (topic_id, topic_body) values (85, 'Clint Eastwood: Out of the Shadows');
insert into topic_tags (topic_id, topic_body) values (86, 'W.R.: Mysteries of the Organism');
insert into topic_tags (topic_id, topic_body) values (87, 'And Then There Were None');
insert into topic_tags (topic_id, topic_body) values (88, 'Dirt');
insert into topic_tags (topic_id, topic_body) values (89, 'Against All Flags');
insert into topic_tags (topic_id, topic_body) values (90, 'Wankers, The (Les branleuses)');
insert into topic_tags (topic_id, topic_body) values (91, 'A Cry in the Wild');
insert into topic_tags (topic_id, topic_body) values (92, 'Yu-Gi-Oh!: Bonds Beyond Time (Gekijouban Yuugiou: Chouyuugou! Jikuu o koeta kizuna)');
insert into topic_tags (topic_id, topic_body) values (93, 'Louis C.K.: Live at the Beacon Theater');
insert into topic_tags (topic_id, topic_body) values (94, 'Death Kiss, The');
insert into topic_tags (topic_id, topic_body) values (95, 'Sky Fighters (Les Chevaliers Du Ciel)');
insert into topic_tags (topic_id, topic_body) values (96, 'Darker Than Night');
insert into topic_tags (topic_id, topic_body) values (97, 'Mindwalk');
insert into topic_tags (topic_id, topic_body) values (98, 'Kedma');
insert into topic_tags (topic_id, topic_body) values (99, 'Jean de Florette');
insert into topic_tags (topic_id, topic_body) values (100, 'Something in the Wind');
-- ---------------------------------------------------------
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (1, 93, 87, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 0, 'Integer.avi', 76, 'ayockley0');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (2, 30, 80, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 0, 'At.avi', 5, 'lbodker1');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (3, 17, 49, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 0, 'QuamPede.jpeg', 85, 'swonfar2');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (4, 17, 67, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 0, 'Est.mp3', 2, 'wmiranda3');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (5, 27, 75, 'Fusce consequat. Nulla nisl. Nunc nisl.', 0, 'AmetEros.mov', 21, 'acrampsy4');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (6, 59, 14, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 0, 'AugueVestibulum.ppt', 100, 'lbartalot5');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (7, 61, 59, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 0, 'Erat.mov', 66, 'corae6');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (8, 70, 10, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 0, 'DiamId.mp3', 27, 'abunstone7');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (9, 39, 48, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 0, 'VestibulumAnte.tiff', 9, 'cmanass8');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (10, 90, 24, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 0, 'SollicitudinUt.avi', 74, 'cwebermann9');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (11, 66, 38, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 0, 'AmetTurpis.jpeg', 61, 'bnelthroppa');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (12, 37, 80, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 0, 'MetusSapienUt.ppt', 79, 'ageharkeb');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (13, 90, 94, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 0, 'TortorDuisMattis.xls', 17, 'dernkec');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (14, 67, 96, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 0, 'DictumstAliquamAugue.pdf', 73, 'splomd');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (15, 10, 87, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 0, 'Donec.mp3', 56, 'gwoolforde');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (16, 54, 81, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 0, 'InterdumVenenatis.xls', 21, 'elebournf');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (17, 39, 2, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 0, 'AliquamErat.avi', 26, 'sarnoudg');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (18, 13, 96, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 0, 'OrciNullamMolestie.png', 85, 'arobeh');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (19, 62, 78, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 0, 'Tortor.tiff', 51, 'rkorejsi');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (20, 5, 96, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 0, 'DuisConsequatDui.mp3', 73, 'kkiezlerj');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (21, 71, 62, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 0, 'Quam.tiff', 21, 'khelixk');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (22, 91, 15, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 0, 'VelIpsum.avi', 87, 'raizikovichl');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (23, 24, 91, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 0, 'Justo.pdf', 92, 'cfonesm');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (24, 21, 93, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 0, 'RutrumNulla.ppt', 16, 'ppuddinn');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (25, 7, 50, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 0, 'TemporConvallis.jpeg', 27, 'rwarmano');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (26, 19, 37, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 0, 'Sociis.mp3', 28, 'hthatchamp');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (27, 44, 39, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 0, 'EuEst.xls', 81, 'mbennitq');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (28, 1, 11, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 0, 'TellusSemper.mpeg', 40, 'ddorbinr');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (29, 41, 73, 'In congue. Etiam justo. Etiam pretium iaculis justo.', 0, 'EratTortorSollicitudin.png', 15, 'cleipelts');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (30, 17, 67, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 0, 'TurpisSed.mpeg', 50, 'lfinlryt');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (31, 96, 26, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 0, 'Vulputate.doc', 97, 'jpowlettu');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (32, 21, 97, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 0, 'RhoncusAliquetPulvinar.mov', 89, 'gmouldsv');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (33, 86, 12, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 0, 'Turpis.mp3', 21, 'cibbesonw');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (34, 42, 97, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 0, 'CubiliaCurae.ppt', 19, 'lverrillsx');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (35, 46, 82, 'In congue. Etiam justo. Etiam pretium iaculis justo.', 0, 'EleifendQuamA.xls', 66, 'ttrattony');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (36, 84, 27, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 0, 'ALibero.ppt', 5, 'skrysztowczykz');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (37, 80, 96, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 0, 'PedeJusto.xls', 14, 'jsharper10');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (38, 93, 48, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 0, 'InFelisEu.mpeg', 100, 'jlaible11');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (39, 9, 48, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 0, 'JustoSit.ppt', 79, 'rtawn12');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (40, 40, 19, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 0, 'AliquamConvallis.xls', 64, 'kjahncke13');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (41, 96, 62, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 0, 'Rhoncus.avi', 70, 'otancock14');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (42, 95, 54, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 0, 'CumSociisNatoque.avi', 55, 'ntyas15');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (43, 32, 94, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 0, 'ConsectetuerAdipiscingElit.txt', 12, 'gsidery16');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (44, 2, 62, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 0, 'AliquetUltricesErat.xls', 18, 'farp17');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (45, 23, 92, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 0, 'MorbiVestibulum.tiff', 15, 'lgiannazzi18');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (46, 94, 64, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 0, 'Quis.tiff', 90, 'rmithan19');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (47, 3, 65, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 0, 'Sapien.ppt', 88, 'gspurrier1a');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (48, 31, 78, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 0, 'Leo.xls', 44, 'rhathwood1b');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (49, 85, 93, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 0, 'Id.mov', 95, 'smazzeo1c');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (50, 19, 82, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 0, 'Primis.mp3', 45, 'tdemiranda1d');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (51, 60, 17, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 0, 'RidiculusMusVivamus.ppt', 99, 'ghayman1e');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (52, 63, 56, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 0, 'PosuereCubiliaCurae.jpeg', 19, 'khails1f');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (53, 72, 35, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 0, 'AugueQuam.mov', 98, 'jkopje1g');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (54, 38, 47, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 0, 'AnteIpsum.gif', 16, 'dflancinbaum1h');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (55, 63, 84, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 0, 'LoremIpsumDolor.ppt', 15, 'dhenryson1i');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (56, 31, 76, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 0, 'LuctusTincidunt.xls', 21, 'ihallet1j');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (57, 32, 52, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 0, 'EleifendDonecUt.doc', 34, 'bfeatherbie1k');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (58, 72, 44, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 0, 'MaurisNonLigula.xls', 77, 'kgillivrie1l');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (59, 74, 2, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 0, 'SemDuis.tiff', 95, 'lriolfi1m');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (60, 14, 49, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 0, 'EtiamPretium.xls', 3, 'lpieche1n');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (61, 19, 56, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 0, 'In.mp3', 99, 'kklawi1o');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (62, 9, 33, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 0, 'InImperdietEt.avi', 42, 'jlacaze1p');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (63, 36, 92, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 0, 'Congue.xls', 83, 'gsenn1q');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (64, 59, 41, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 0, 'CongueEget.avi', 71, 'mentreis1r');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (65, 49, 41, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 0, 'Quis.doc', 37, 'cmalone1s');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (66, 73, 10, 'In congue. Etiam justo. Etiam pretium iaculis justo.', 0, 'IntegerAliquet.pdf', 94, 'zwhannel1t');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (67, 66, 90, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 0, 'Cras.avi', 72, 'cbulch1u');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (68, 23, 96, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 0, 'QuamNecDui.avi', 99, 'llittlejohn1v');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (69, 84, 35, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 0, 'IdConsequat.jpeg', 54, 'atolley1w');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (70, 80, 100, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 0, 'Eu.avi', 48, 'whugonet1x');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (71, 67, 28, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 0, 'AliquetPulvinarSed.jpeg', 36, 'edeakins1y');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (72, 73, 65, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 0, 'MassaVolutpatConvallis.mp3', 53, 'iroadnight1z');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (73, 87, 27, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 0, 'Interdum.doc', 47, 'bstarrs20');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (74, 7, 29, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 0, 'MaecenasTristiqueEst.xls', 18, 'ipopplestone21');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (75, 43, 74, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 0, 'Felis.avi', 72, 'rdeporte22');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (76, 98, 13, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 0, 'SapienNonMi.pdf', 1, 'cfissenden23');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (77, 67, 40, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 0, 'CongueRisus.xls', 86, 'nwaterhous24');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (78, 13, 11, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 0, 'Ipsum.tiff', 83, 'asimounet25');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (79, 7, 51, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 0, 'QuamSuspendissePotenti.xls', 97, 'kwestwick26');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (80, 29, 95, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 0, 'Ut.xls', 90, 'ccluney27');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (81, 70, 17, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 0, 'Montes.tiff', 77, 'eswainger28');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (82, 28, 52, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 0, 'EuSapienCursus.jpeg', 69, 'ndonnison29');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (83, 93, 48, 'In congue. Etiam justo. Etiam pretium iaculis justo.', 0, 'AliquamEratVolutpat.ppt', 27, 'agunner2a');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (84, 57, 75, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 0, 'ArcuSed.avi', 80, 'mgippes2b');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (85, 84, 3, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 0, 'VelLectusIn.jpeg', 86, 'rcarah2c');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (86, 5, 26, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 0, 'EgetTincidunt.mp3', 21, 'bgarrals2d');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (87, 42, 54, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 0, 'Platea.jpeg', 92, 'rholdren2e');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (88, 64, 11, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 0, 'QuisAugueLuctus.ppt', 48, 'derrington2f');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (89, 11, 7, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 0, 'DolorMorbiVel.ppt', 89, 'ldalziell2g');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (90, 4, 35, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 0, 'Duis.jpeg', 2, 'gsisey2h');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (91, 26, 40, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 0, 'Lobortis.mp3', 35, 'mkibel2i');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (92, 69, 32, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 0, 'Etiam.xls', 96, 'mhellen2j');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (93, 99, 73, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 0, 'SollicitudinVitaeConsectetuer.ppt', 91, 'kwittleton2k');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (94, 77, 74, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 0, 'Ante.xls', 27, 'mbussens2l');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (95, 89, 98, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 0, 'InLibero.ppt', 47, 'vguyan2m');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (96, 33, 66, 'Fusce consequat. Nulla nisl. Nunc nisl.', 0, 'TinciduntEgetTempus.jpeg', 23, 'dohannen2n');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (97, 18, 6, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 0, 'AliquetUltrices.tiff', 94, 'dempleton2o');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (98, 59, 50, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 0, 'Iaculis.ppt', 79, 'smainstone2p');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (99, 11, 18, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 0, 'OdioOdioElementum.xls', 29, 'cosler2q');
insert into post (post_id, author_id, title, body, post_hits, image_upload_name, post_topic, nick_name) values (100, 62, 12, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 0, 'In.txt', 80, 'shamblen2r');
-- --------------------------------------------------------
insert into user_followings (followings_id, follower_id, followee_id) values (1, 28, 65);
insert into user_followings (followings_id, follower_id, followee_id) values (2, 80, 8);
insert into user_followings (followings_id, follower_id, followee_id) values (3, 54, 3);
insert into user_followings (followings_id, follower_id, followee_id) values (4, 56, 66);
insert into user_followings (followings_id, follower_id, followee_id) values (5, 57, 90);
insert into user_followings (followings_id, follower_id, followee_id) values (6, 92, 37);
insert into user_followings (followings_id, follower_id, followee_id) values (7, 89, 9);
insert into user_followings (followings_id, follower_id, followee_id) values (8, 3, 32);
insert into user_followings (followings_id, follower_id, followee_id) values (9, 59, 83);
insert into user_followings (followings_id, follower_id, followee_id) values (10, 83, 83);
insert into user_followings (followings_id, follower_id, followee_id) values (11, 76, 47);
insert into user_followings (followings_id, follower_id, followee_id) values (12, 92, 38);
insert into user_followings (followings_id, follower_id, followee_id) values (13, 52, 71);
insert into user_followings (followings_id, follower_id, followee_id) values (14, 28, 29);
insert into user_followings (followings_id, follower_id, followee_id) values (15, 40, 87);
insert into user_followings (followings_id, follower_id, followee_id) values (16, 13, 46);
insert into user_followings (followings_id, follower_id, followee_id) values (17, 60, 38);
insert into user_followings (followings_id, follower_id, followee_id) values (18, 64, 45);
insert into user_followings (followings_id, follower_id, followee_id) values (19, 94, 82);
insert into user_followings (followings_id, follower_id, followee_id) values (20, 23, 77);
insert into user_followings (followings_id, follower_id, followee_id) values (21, 67, 34);
insert into user_followings (followings_id, follower_id, followee_id) values (22, 82, 73);
insert into user_followings (followings_id, follower_id, followee_id) values (23, 85, 92);
insert into user_followings (followings_id, follower_id, followee_id) values (24, 74, 62);
insert into user_followings (followings_id, follower_id, followee_id) values (25, 95, 90);
insert into user_followings (followings_id, follower_id, followee_id) values (26, 40, 29);
insert into user_followings (followings_id, follower_id, followee_id) values (27, 49, 25);
insert into user_followings (followings_id, follower_id, followee_id) values (28, 26, 50);
insert into user_followings (followings_id, follower_id, followee_id) values (29, 20, 26);
insert into user_followings (followings_id, follower_id, followee_id) values (30, 7, 63);
insert into user_followings (followings_id, follower_id, followee_id) values (31, 84, 3);
insert into user_followings (followings_id, follower_id, followee_id) values (32, 81, 77);
insert into user_followings (followings_id, follower_id, followee_id) values (33, 93, 71);
insert into user_followings (followings_id, follower_id, followee_id) values (34, 11, 23);
insert into user_followings (followings_id, follower_id, followee_id) values (35, 67, 14);
insert into user_followings (followings_id, follower_id, followee_id) values (36, 20, 13);
insert into user_followings (followings_id, follower_id, followee_id) values (37, 54, 57);
insert into user_followings (followings_id, follower_id, followee_id) values (38, 58, 67);
insert into user_followings (followings_id, follower_id, followee_id) values (39, 44, 12);
insert into user_followings (followings_id, follower_id, followee_id) values (40, 17, 86);
insert into user_followings (followings_id, follower_id, followee_id) values (41, 94, 31);
insert into user_followings (followings_id, follower_id, followee_id) values (42, 80, 64);
insert into user_followings (followings_id, follower_id, followee_id) values (44, 48, 72);
insert into user_followings (followings_id, follower_id, followee_id) values (45, 24, 66);
insert into user_followings (followings_id, follower_id, followee_id) values (46, 67, 53);
insert into user_followings (followings_id, follower_id, followee_id) values (47, 39, 91);
insert into user_followings (followings_id, follower_id, followee_id) values (48, 44, 74);
insert into user_followings (followings_id, follower_id, followee_id) values (49, 41, 58);
insert into user_followings (followings_id, follower_id, followee_id) values (50, 39, 6);
insert into user_followings (followings_id, follower_id, followee_id) values (51, 68, 31);
insert into user_followings (followings_id, follower_id, followee_id) values (52, 94, 6);
insert into user_followings (followings_id, follower_id, followee_id) values (53, 50, 84);
insert into user_followings (followings_id, follower_id, followee_id) values (54, 84, 17);
insert into user_followings (followings_id, follower_id, followee_id) values (55, 10, 68);
insert into user_followings (followings_id, follower_id, followee_id) values (56, 17, 65);
insert into user_followings (followings_id, follower_id, followee_id) values (57, 88, 74);
insert into user_followings (followings_id, follower_id, followee_id) values (58, 21, 10);
insert into user_followings (followings_id, follower_id, followee_id) values (59, 54, 78);
insert into user_followings (followings_id, follower_id, followee_id) values (60, 95, 10);
insert into user_followings (followings_id, follower_id, followee_id) values (61, 57, 94);
insert into user_followings (followings_id, follower_id, followee_id) values (62, 16, 16);
insert into user_followings (followings_id, follower_id, followee_id) values (63, 57, 54);
insert into user_followings (followings_id, follower_id, followee_id) values (64, 44, 8);
insert into user_followings (followings_id, follower_id, followee_id) values (65, 96, 21);
insert into user_followings (followings_id, follower_id, followee_id) values (66, 89, 46);
insert into user_followings (followings_id, follower_id, followee_id) values (67, 86, 54);
insert into user_followings (followings_id, follower_id, followee_id) values (68, 28, 5);
insert into user_followings (followings_id, follower_id, followee_id) values (69, 10, 49);
insert into user_followings (followings_id, follower_id, followee_id) values (70, 25, 45);
insert into user_followings (followings_id, follower_id, followee_id) values (71, 73, 10);
insert into user_followings (followings_id, follower_id, followee_id) values (72, 98, 25);
insert into user_followings (followings_id, follower_id, followee_id) values (73, 31, 36);
insert into user_followings (followings_id, follower_id, followee_id) values (74, 74, 20);
insert into user_followings (followings_id, follower_id, followee_id) values (75, 54, 93);
insert into user_followings (followings_id, follower_id, followee_id) values (76, 1, 93);
insert into user_followings (followings_id, follower_id, followee_id) values (77, 94, 92);
insert into user_followings (followings_id, follower_id, followee_id) values (78, 81, 72);
insert into user_followings (followings_id, follower_id, followee_id) values (79, 78, 72);
insert into user_followings (followings_id, follower_id, followee_id) values (80, 74, 10);
insert into user_followings (followings_id, follower_id, followee_id) values (81, 37, 14);
insert into user_followings (followings_id, follower_id, followee_id) values (82, 23, 73);
insert into user_followings (followings_id, follower_id, followee_id) values (83, 23, 36);
insert into user_followings (followings_id, follower_id, followee_id) values (84, 34, 2);
insert into user_followings (followings_id, follower_id, followee_id) values (85, 9, 64);
insert into user_followings (followings_id, follower_id, followee_id) values (86, 72, 32);
insert into user_followings (followings_id, follower_id, followee_id) values (87, 16, 87);
insert into user_followings (followings_id, follower_id, followee_id) values (88, 46, 26);
insert into user_followings (followings_id, follower_id, followee_id) values (89, 19, 35);
insert into user_followings (followings_id, follower_id, followee_id) values (90, 72, 96);
insert into user_followings (followings_id, follower_id, followee_id) values (91, 18, 22);
insert into user_followings (followings_id, follower_id, followee_id) values (92, 15, 74);
insert into user_followings (followings_id, follower_id, followee_id) values (93, 1, 44);
insert into user_followings (followings_id, follower_id, followee_id) values (94, 2, 85);
insert into user_followings (followings_id, follower_id, followee_id) values (95, 32, 82);
insert into user_followings (followings_id, follower_id, followee_id) values (96, 6, 36);
insert into user_followings (followings_id, follower_id, followee_id) values (97, 11, 83);
insert into user_followings (followings_id, follower_id, followee_id) values (98, 39, 31);
insert into user_followings (followings_id, follower_id, followee_id) values (100, 7, 51);
insert into user_followings (followings_id, follower_id, followee_id) values (101, 101, 2);
insert into user_followings (followings_id, follower_id, followee_id) values (102, 101, 3);
insert into user_followings (followings_id, follower_id, followee_id) values (103, 101, 4);
insert into user_followings (followings_id, follower_id, followee_id) values (104, 101, 5);
insert into user_followings (followings_id, follower_id, followee_id) values (105, 101, 6);
insert into user_followings (followings_id, follower_id, followee_id) values (106, 101, 7);
insert into user_followings (followings_id, follower_id, followee_id) values (108, 101, 9);
insert into user_followings (followings_id, follower_id, followee_id) values (109, 101, 10);
insert into user_followings (followings_id, follower_id, followee_id) values (110, 101, 11);

-- --------------------------------------------------------

